@echo off
REM Ensure the working directory is the same as the batch file location
cd /d "%~dp0"

REM --- CHECK FOR UPDATE & DOWNLOAD IF NEWER (NO LAUNCH) ---
echo Checking for updates to Windows_Maintenance_Tool.ps1 and batch launchers...
PowerShell.exe -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference='Stop'; [Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12; $local='Windows_Maintenance_Tool.ps1'; $bat='Start_Windows_Maintenance_Tool.bat'; $urlPs='https://raw.githubusercontent.com/ios12checker/Windows-Maintenance-Tool/main/Windows_Maintenance_Tool.ps1'; $urlBat='https://raw.githubusercontent.com/ios12checker/Windows-Maintenance-Tool/main/Start_Windows_Maintenance_Tool.bat'; $localVer=[version]'0.0'; if(Test-Path $local){$lc=Get-Content $local -Raw; $m1=[regex]::Match($lc,'\$AppVersion\s*=\s*\"([\d\.]+)\"',[System.Text.RegularExpressions.RegexOptions]::IgnoreCase); if($m1.Success){$localVer=[version]$m1.Groups[1].Value} else {$m2=[regex]::Match($lc,'Windows\s+Maintenance\s+Tool.*?v(\d+(\.\d+)+)',[System.Text.RegularExpressions.RegexOptions]::IgnoreCase); if($m2.Success){$localVer=[version]$m2.Groups[1].Value}}} $resp=$null; try{$resp=Invoke-WebRequest -Uri $urlPs -UseBasicParsing -ErrorAction Stop}catch{Write-Warning ('PS1 download failed: {0}' -f $_.Exception.Message)} if($resp -and $resp.Content){ $remoteVer=$null; if($resp.Content -match '\$AppVersion\s*=\s*\"([\d\.]+)\"'){ $remoteVer=[version]$matches[1] } elseif($resp.Content -match 'Windows\s+Maintenance\s+Tool.*?v(\d+(\.\d+)+)'){ $remoteVer=[version]$matches[1] } $shouldUpdate=$true; if($remoteVer){ if($remoteVer -gt $localVer){$shouldUpdate=$true} elseif($remoteVer -eq $localVer){$shouldUpdate=$false; Write-Host ('Already up to date. v{0}' -f $localVer)} else {$shouldUpdate=$false; Write-Host ('Local version (v{0}) is newer than remote (v{1}); no action taken.' -f $localVer,$remoteVer)} } else { Write-Host 'Remote version unknown; updating from latest main branch payload.'; $shouldUpdate=$true } if($shouldUpdate){ Set-Content -Path $local -Value $resp.Content -Encoding UTF8; if($remoteVer){ Write-Host ('Updated PS1 to v{0} (was v{1}).' -f $remoteVer,$localVer) } else { Write-Host 'Updated PS1 from latest main branch (version unknown in payload).' } } } else { Write-Host 'Skipping PS1 update (no content downloaded).' } try{ $batResp = Invoke-WebRequest -Uri $urlBat -UseBasicParsing -ErrorAction Stop; if($batResp -and $batResp.Content -match 'Windows_Maintenance_Tool.ps1'){ Set-Content -Path $bat -Value $batResp.Content -Encoding ASCII; Write-Host 'Batch launcher updated.' } else { Write-Warning 'Batch launcher download looked invalid; skipped writing.' } }catch{Write-Warning ('Batch launcher update failed: {0}' -f $_.Exception.Message)}"

echo.
echo Done. Press any key to exit.
pause >nul
EXIT
